### Required Assignment 23.1: Translating Data into Text

**Expected Time = 60 minutes**

**Total Points = 20**

In this assignment, you will generate a narrative from a dataframe without explicitly crafting a prompt. You will utilize the `pandas` library to convert the dataframe to a format that the `OpenAI` can interpret. Next you will use the OpenAI API to train you model to generate a narrative from the data.

#### Index

- [Problem 1](#-Problem-1)
- [Problem 2](#-Problem-2)
- [Problem 3](#-Problem-3)

## The Dataset

For this assignment, you will be using a dataset that contains list of video games with global sales greater than 100,000 copies. The fields in this dataset include:

- Rank: The ranking of overall sales
- Name: The name of the video game
- Platform: The platform of the games release (i.e. PC,PS4, etc.)
- Year: The year of the game's release
- Genre: The genre of the game
- Publisher: The publisher of the game
- NA_Sales: Sales in North America (in millions)
- EU_Sales: Sales in Europe (in millions)
- JP_Sales: Sales in Japan (in millions)
- Other_Sales: Sales in the rest of the world (in millions)
- Global_Sales: Total worldwide sales.


Run the code cell below to import the necessary libraries and the dataset.

In [2]:
!pip install groq

Collecting groq
  Downloading groq-1.4.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.18)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Downloading groq-1.4.0-py3-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 3.6 MB/s eta 0:00:00
Installing collected packages: groq
Successfully installed groq-1.4.0

In [1]:
import pandas as pd
import openai
from openai import OpenAI

# Sample dataset to feed the program
data = pd.read_csv('/content/sample_data/vgsales.csv')

In [2]:
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

[Back to top](#-Index)

### Problem 1

#### Total Sale Calculation

**5 Points**


In the code cell below, use the `groupby` function on the `data` dataframe to calculate the total `Global_Sales` for each `Genre` of video games and assign the result to the dataframe `total_sales` below. Ensure to use the function `reset_index` with default arguments to reset the index of the dataframe.

In [3]:
### GRADED
total_sales = data.groupby('Genre')['Global_Sales'].sum()
# YOUR CODE HERE
total_sales=total_sales.reset_index()

### ANSWER CHECK
total_sales

                          Genre  Global_Sales
0                        Action       1751.18
1                     Adventure        238.92
2                      Fighting        448.91
3                  Idea Factory          0.00
4                          Misc        809.96
5                      Platform        831.37
6                        Puzzle        244.95
7                        Racing        732.04
8                  Role-Playing        927.37
9                       Shooter       1037.37
10                   Simulation        392.20
11  Sony Computer Entertainment          0.00
12                       Sports       1330.93
13                     Strategy        175.12

[Back to top](#-Index)

### Problem 2

#### Data Preparation

**5 Points**

Next, you will convert the `total_sales` dataframe to a string format, which can be passed directly to the OpenAI library.

In the code cell below, use the `to_string` function on the `total_sales` dataframe with argument `index` equal to `False`. Additionally, to ensure that your data is formatted correctly, use the `replace` function with argument `'\n', ' '` to delete any newline characters.

Next, define a dictionary `data_dict` with key equal to `data` and field equal to `data_string`.

In [4]:
### GRADED
data_string = ...
data_dict = ...
# YOUR CODE HERE
data_string = total_sales.to_string(index=False).replace('\n','')

data_dict={
  "data": data_string,
}

### ANSWER CHECK
data_dict

{'data': '                      Genre  Global_Sales                     Action       1751.18                  Adventure        238.92                   Fighting        448.91               Idea Factory          0.00                       Misc        809.96                   Platform        831.37                     Puzzle        244.95                     Racing        732.04               Role-Playing        927.37                    Shooter       1037.37                 Simulation        392.20Sony Computer Entertainment          0.00                     Sports       1330.93                   Strategy        175.12'}

[Back to top](#-Index)

### Problem 3

#### Obtaining Your OpenAI API Key

**10 Points**

To use the OpenAI library, you are required to obtain an API key. You will obtain a free API key from Groq. To access Groq and get your personal API key, follow the steps below:

1. **Create an OpenAI Account:**
Visit the [Groq website](https://console.groq.com/login) and sign up if you don't already have an account.
2. **Log In:**
Log in using your credentials at the Groq platform.
3. **Navigate to the API Dashboard:**
Once logged in, navigate to the [Groq playground](https://console.groq.com/playground).
4. **Generate an API Key:**
In the menu on the left, click on API Keys, and click on the Create API key button. Copy your API key and store it in a secure place.


You can now use this API key in your applications to authenticate requests to OpenAI's API.

Once you have generated your API key, in the code cell below, invoke the `Groq` function and assign to the `api_key` argument your API key as a string followed by a comma. Assign the function call to the `client` variable below.

In [ ]:
pip install openai

In [5]:
### GRADED
import os
# YOUR CODE HERE
# Please replace 'YOUR_OPENAI_API_KEY_HERE' with your actual OpenAI API key.

#client = OpenAI(api_key="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")
client = OpenAI(api_key="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",    base_url="https://api.groq.com/openai/v1")

### ANSWER CHECK
client

In [6]:
# Print out what all models this client can access with authentication
client_model_list = client.models.list()
# convert to a dataframe
df = pd.DataFrame(client_model_list.data)
df.index = range(len(df))
# check it contains llama.
df

,0,1,2,3,4,5,6,7
0,"(id, qwen/qwen3-32b)","(created, 1748396646)","(object, model)","(owned_by, Alibaba Cloud)","(active, True)","(context_window, 131072)","(public_apps, None)","(max_completion_tokens, 40960)"
1,"(id, canopylabs/orpheus-v1-english)","(created, 1766186316)","(object, model)","(owned_by, Canopy Labs)","(active, True)","(context_window, 4000)","(public_apps, None)","(max_completion_tokens, 50000)"
2,"(id, meta-llama/llama-prompt-guard-2-86m)","(created, 1748632165)","(object, model)","(owned_by, Meta)","(active, True)","(context_window, 512)","(public_apps, None)","(max_completion_tokens, 512)"
3,"(id, openai/gpt-oss-120b)","(created, 1754408224)","(object, model)","(owned_by, OpenAI)","(active, True)","(context_window, 131072)","(public_apps, None)","(max_completion_tokens, 65536)"
4,"(id, openai/gpt-oss-20b)","(created, 1754407957)","(object, model)","(owned_by, OpenAI)","(active, True)","(context_window, 131072)","(public_apps, None)","(max_completion_tokens, 65536)"
5,"(id, groq/compound)","(created, 1756949530)","(object, model)","(owned_by, Groq)","(active, True)","(context_window, 131072)","(public_apps, None)","(max_completion_tokens, 8192)"
6,"(id, llama-3.3-70b-versatile)","(created, 1733447754)","(object, model)","(owned_by, Meta)","(active, True)","(context_window, 131072)","(public_apps, None)","(max_completion_tokens, 32768)"
7,"(id, meta-llama/llama-prompt-guard-2-22m)","(created, 1748632101)","(object, model)","(owned_by, Meta)","(active, True)","(context_window, 512)","(public_apps, None)","(max_completion_tokens, 512)"
8,"(id, meta-llama/llama-4-scout-17b-16e-instruct)","(created, 1743874824)","(object, model)","(owned_by, Meta)","(active, True)","(context_window, 131072)","(public_apps, None)","(max_completion_tokens, 8192)"
9,"(id, whisper-large-v3-turbo)","(created, 1728413088)","(object, model)","(owned_by, OpenAI)","(active, True)","(context_window, 448)","(public_apps, None)","(max_completion_tokens, 448)"
10,"(id, groq/compound-mini)","(created, 1756949707)","(object, model)","(owned_by, Groq)","(active, True)","(context_window, 131072)","(public_apps, None)","(max_completion_tokens, 8192)"
11,"(id, llama-3.1-8b-instant)","(created, 1693721698)","(object, model)","(owned_by, Meta)","(active, True)","(context_window, 131072)","(public_apps, None)","(max_completion_tokens, 131072)"
12,"(id, openai/gpt-oss-safeguard-20b)","(created, 1761708789)","(object, model)","(owned_by, OpenAI)","(active, True)","(context_window, 131072)","(public_apps, None)","(max_completion_tokens, 65536)"
13,"(id, canopylabs/orpheus-arabic-saudi)","(created, 1765926439)","(object, model)","(owned_by, Canopy Labs)","(active, True)","(context_window, 4000)","(public_apps, None)","(max_completion_tokens, 50000)"
14,"(id, allam-2-7b)","(created, 1737672203)","(object, model)","(owned_by, SDAIA)","(active, True)","(context_window, 4096)","(public_apps, None)","(max_completion_tokens, 4096)"
15,"(id, whisper-large-v3)","(created, 1693721698)","(object, model)","(owned_by, OpenAI)","(active, True)","(context_window, 448)","(public_apps, None)","(max_completion_tokens, 448)"

In [7]:
for m in list((client.models.list()).data)[:20]:
    print(m.id)

qwen/qwen3-32b
groq/compound-mini
whisper-large-v3-turbo
openai/gpt-oss-120b
openai/gpt-oss-20b
meta-llama/llama-prompt-guard-2-22m
meta-llama/llama-4-scout-17b-16e-instruct
canopylabs/orpheus-v1-english
llama-3.3-70b-versatile
groq/compound
openai/gpt-oss-safeguard-20b
canopylabs/orpheus-arabic-saudi
meta-llama/llama-prompt-guard-2-86m
whisper-large-v3
allam-2-7b
llama-3.1-8b-instant

In [8]:
print(openai.__version__)

2.40.0

[Back to top](#-Index)

### Problem 4

#### Generating the Text Narrative from Your Data

**This question is not graded**

In the code cell below you will generate a narrative based on the data in the dataframe using OpenAI.

Complete the code below using the instructions below:

- Use the `chat.completions.create()` method on the `client` object to send a chat request and receive a response.
- Inside the `chat.completions.create()` method, set the parameter `messages` to defines the conversation history or prompt that will be sent to the model equal to `{"role": "user", "content":  f"Analyze the following data: {data_object['data']}"}`.
- Inside the `chat.completions.create()` method, set the parameter `model` equal to `"llama3-8b-8192"`.

Assign this object to the `chat_completion` variable below.


Once you are done, run the code cell to visualize the narrative.

Lastly, ensure that your narrative is formatted correctly.

In [9]:
# check what models my account can access
models = client.models.list()
print(models)

SyncPage[Model](data=[Model(id='openai/gpt-oss-safeguard-20b', created=1761708789, object='model', owned_by='OpenAI', active=True, context_window=131072, public_apps=None, max_completion_tokens=65536), Model(id='whisper-large-v3-turbo', created=1728413088, object='model', owned_by='OpenAI', active=True, context_window=448, public_apps=None, max_completion_tokens=448), Model(id='allam-2-7b', created=1737672203, object='model', owned_by='SDAIA', active=True, context_window=4096, public_apps=None, max_completion_tokens=4096), Model(id='openai/gpt-oss-20b', created=1754407957, object='model', owned_by='OpenAI', active=True, context_window=131072, public_apps=None, max_completion_tokens=65536), Model(id='meta-llama/llama-prompt-guard-2-86m', created=1748632165, object='model', owned_by='Meta', active=True, context_window=512, public_apps=None, max_completion_tokens=512), Model(id='whisper-large-v3', created=1693721698, object='model', owned_by='OpenAI', active=True, context_window=448, public_apps=None, max_completion_tokens=448), Model(id='qwen/qwen3-32b', created=1748396646, object='model', owned_by='Alibaba Cloud', active=True, context_window=131072, public_apps=None, max_completion_tokens=40960), Model(id='llama-3.1-8b-instant', created=1693721698, object='model', owned_by='Meta', active=True, context_window=131072, public_apps=None, max_completion_tokens=131072), Model(id='canopylabs/orpheus-arabic-saudi', created=1765926439, object='model', owned_by='Canopy Labs', active=True, context_window=4000, public_apps=None, max_completion_tokens=50000), Model(id='groq/compound', created=1756949530, object='model', owned_by='Groq', active=True, context_window=131072, public_apps=None, max_completion_tokens=8192), Model(id='meta-llama/llama-4-scout-17b-16e-instruct', created=1743874824, object='model', owned_by='Meta', active=True, context_window=131072, public_apps=None, max_completion_tokens=8192), Model(id='llama-3.3-70b-versatile', created=1733447754, object='model', owned_by='Meta', active=True, context_window=131072, public_apps=None, max_completion_tokens=32768), Model(id='openai/gpt-oss-120b', created=1754408224, object='model', owned_by='OpenAI', active=True, context_window=131072, public_apps=None, max_completion_tokens=65536), Model(id='canopylabs/orpheus-v1-english', created=1766186316, object='model', owned_by='Canopy Labs', active=True, context_window=4000, public_apps=None, max_completion_tokens=50000), Model(id='meta-llama/llama-prompt-guard-2-22m', created=1748632101, object='model', owned_by='Meta', active=True, context_window=512, public_apps=None, max_completion_tokens=512), Model(id='groq/compound-mini', created=1756949707, object='model', owned_by='Groq', active=True, context_window=131072, public_apps=None, max_completion_tokens=8192)], object='list')

In [10]:
# command to get all variable names and values  in this notebook
%whos

Variable            Type               Data/Info
------------------------------------------------
OpenAI              type               <class 'openai.OpenAI'>
client              OpenAI             <openai.OpenAI object at 0x7c2d46b3faa0>
client_model_list   SyncPage[Model]    SyncPage[Model](data=[Mod<...>ens=448)], object='list')
data                DataFrame                  Rank             <...>[16598 rows x 11 columns]
data_dict           dict               n=1
data_string         str                                      Gen<...>   Strategy        175.12
df                  DataFrame                                   <...>completion_tokens, 448)
m                   Model              Model(id='llama-3.1-8b-in<...>completion_tokens=131072)
models              SyncPage[Model]    SyncPage[Model](data=[Mod<...>ns=8192)], object='list')
openai              module             <module 'openai' from '/u<...>ages/openai/__init__.py'>
os                  module             <module 'os' (frozen)>
pd                  module             <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
total_sales         DataFrame                                   <...>   Strategy        175.12

In [11]:
total_sales

                          Genre  Global_Sales
0                        Action       1751.18
1                     Adventure        238.92
2                      Fighting        448.91
3                  Idea Factory          0.00
4                          Misc        809.96
5                      Platform        831.37
6                        Puzzle        244.95
7                        Racing        732.04
8                  Role-Playing        927.37
9                       Shooter       1037.37
10                   Simulation        392.20
11  Sony Computer Entertainment          0.00
12                       Sports       1330.93
13                     Strategy        175.12

In [12]:
#data.groupby("Genre")["Global_Sales"].sum().reset_index()
data[data["Genre"]=="Sports"]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
13,14,Wii Fit,Wii,2007,Sports,Nintendo,8.94,8.03,3.60,2.15,22.72
14,15,Wii Fit Plus,Wii,2009,Sports,Nintendo,9.09,8.59,2.53,1.79,22.00
77,78,FIFA 16,PS4,2015,Sports,Electronic Arts,1.11,6.06,0.06,1.26,8.49
...,...,...,...,...,...,...,...,...,...,...,...
16576,16579,Rugby Challenge 3,XOne,2016,Sports,Alternative Software,0.00,0.01,0.00,0.00,0.01
16578,16581,Outdoors Unleashed: Africa 3D,3DS,2011,Sports,Mastiff,0.01,0.00,0.00,0.00,0.01
16579,16582,PGA European Tour,N64,2000,Sports,Infogrames,0.01,0.00,0.00,0.00,0.01
16581,16584,Fit & Fun,Wii,2011,Sports,Unknown,0.00,0.01,0.00,0.00,0.01
16587,16590,Mezase!! Tsuri Master DS,DS,2009,Sports,Hudson Soft,0.00,0.00,0.01,0.00,0.01

In [20]:
## GRADED
narrative = ...
# YOUR CODE HERE
chat_completion=client.chat.completions.create(model = "llama-3.1-8b-instant",
    messages=[{"role": "user",
               "content":  f"Analyze the following data: {data_dict['data']}"
               #"content":  f"Which genres did not make much money as per this data ? : {total_sales}"
             }])

print(chat_completion.choices[0].message.content)

Based on the provided data, here's an analysis of the information:

1. **Genre-wise Sales:**
   - The top-selling genre is Action with sales of 1751.18 units.
   - Following closely is Role-Playing with sales of 927.37 units.
   - Racing and Simulation have relatively high sales with 732.04 and 392.20 units respectively.
   - Genre types like Adventure, Fighting, Platform, Puzzle, Shooter, and Strategy have relatively low sales, with the latter being the least selling at 175.12 units.

2. **Publisher-wise Sales:**
   - Idea Factory is the only publisher listed, and they have zero sales globally.
   - Sony Computer Entertainment also has zero sales globally.

3. **Global Sales:**
   - Total global sales are not provided in the given data.

4. **Top-selling Genre Comparison:**
   - If we compare the top-selling genre (Action) with the others, the difference in sales is quite significant:
     1751.18 (Action) - 927.37 (Role-Playing) = 823.81 units.
     1751.18 (Action) - 732.04 (Racing) = 1019.14 units.
     1751.18 (Action) - 392.20 (Simulation) = 1358.98 units.

5. **Sales Distribution:**
   - The sales are skewed towards Action games. The top 3 genres (Action, Role-Playing, and Racing) account for almost 50% of the total sales.
   - This might indicate a preference for these types of games in the global market.

Please note that there are several limitations and assumptions in this analysis due to the lack of information about the total global sales.

In [22]:
total_sales.sort_values(by="Global_Sales")

                          Genre  Global_Sales
3                  Idea Factory          0.00
11  Sony Computer Entertainment          0.00
13                     Strategy        175.12
1                     Adventure        238.92
6                        Puzzle        244.95
10                   Simulation        392.20
2                      Fighting        448.91
7                        Racing        732.04
4                          Misc        809.96
5                      Platform        831.37
8                  Role-Playing        927.37
9                       Shooter       1037.37
12                       Sports       1330.93
0                        Action       1751.18

In [18]:
chat_completion=client.chat.completions.create(model = "llama-3.3-70b-versatile",
messages=[{"role": "user",
               "content":  f"Analyze the following data: {data_dict['data']}"
               #"content":  f"Which genres did not make much money as per this data ? : {total_sales}"
             }])

print(chat_completion.choices[0].message.content)

The provided data appears to be related to video game sales, categorized by genre. Here's a concise analysis of the data:

**Top 3 Genres by Global Sales:**

1. **Sports**: 1330.93
2. **Shooter**: 1037.37
3. **Action**: 1751.18 (However, Action has the highest sales, so it should be at the top)

 Corrected Top 3:
1. **Action**: 1751.18
2. **Sports**: 1330.93
3. **Shooter**: 1037.37

**Lowest Sales:**

1. **Idea Factory** and **Sony Computer Entertainment**: 0.00 (These appear to be publishers or developers rather than genres, and their sales are not applicable in this context)
2. **Strategy**: 175.12 (Among genres, Strategy has the lowest sales)

**Middle Tier:**

Several genres have sales between 200-900, including Adventure, Fighting, Platform, Puzzle, Racing, Role-Playing, and Simulation. These genres seem to have a moderate level of sales.

**Insights:**

* The data suggests that Action games are the best-selling genre, followed by Sports and Shooter games.
* Some genres, like Strategy and Idea Factory (which is not a genre), have very low sales.
* The data may not be comprehensive, as it only includes a limited number of genres and does not account for other factors that could influence sales, such as platform, release date, or marketing efforts.

In [50]:
chat_completion=client.chat.completions.create(model = "llama-3.3-70b-versatile",
messages=[{"role": "user",
               "content":  f"Analyze the following data: {data_dict['data']}"
               #"content":  f"Which genres did not make much money as per this data ? : {total_sales}"
             }])

print(chat_completion.choices[0].message.content)

The given data appears to be a list of video game genres and their corresponding global sales figures. Here's a breakdown of the analysis:

1. **Top-selling genres:**
   - The top 3 best-selling genres are:
     1. Sports: $1330.93 million
     2. Action: $1037.37 million (also includes another entry with $1751.18 million, possibly due to a categorization error)
     3. Role-Playing: $927.37 million

2. **Lowest-selling genres:**
   - The bottom 3 lowest-selling genres are:
     1. Idea Factory: $0.00 million
     2. Sony Computer Entertainment: $0.00 million (this is likely an incorrect categorization, as Sony Computer Entertainment is a video game publisher, not a genre)
     3. Strategy: $175.12 million

3. **Genre distribution:**
   - The data shows a diverse range of genres, indicating a varied market with different consumer preferences.
   - Some genres, like Action and Sports, seem to be more popular, while others, like Idea Factory and Strategy, have significantly lower sales.

4. **Potential errors:**
   - There appears to be a duplication in the Action genre, with two separate entries ($1751.18 million and $1037.37 million). This might be due to a categorization error or incomplete data.
   - Sony Computer Entertainment is listed as a genre, but it's actually a video game publisher. This entry should be removed from the analysis.

5. **Market trends:**
   - The data suggests that Sports and Action games are in high demand, which could indicate a market trend towards fast-paced, competitive, or action-oriented games.
   - The relatively low sales of genres like Strategy and Puzzle might indicate a shift in consumer preferences or a lack of engaging titles in these categories.

In [17]:
data_dict['data']

'                      Genre  Global_Sales                     Action       1751.18                  Adventure        238.92                   Fighting        448.91               Idea Factory          0.00                       Misc        809.96                   Platform        831.37                     Puzzle        244.95                     Racing        732.04               Role-Playing        927.37                    Shooter       1037.37                 Simulation        392.20Sony Computer Entertainment          0.00                     Sports       1330.93                   Strategy        175.12'

In [14]:
text = str(data_dict['data'])
print(len(text))

615