<a href="https://colab.research.google.com/github/Subroy1/MSAI_AllPracticeModules/blob/main/Module12/Module12_Nearest_Negihbors_colab_activity12_1%5B1%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Colab activity 12.1:  Introduction to K-Nearest Neighbors


**Expected Time: 60 Minutes**



This activity is meant to introduce you to the `KNeighborsClassifier` from scikit-learn.  You will build a few different versions, changing values for `k` and examining performance.  You will also preprocess your data by scaling so as to improve the performance of your classifier.

#### Index

- [Problem 1](#-Problem-1)
- [Problem 2](#-Problem-2)
- [Problem 3](#-Problem-3)
- [Problem 4](#-Problem-4)
- [Problem 5](#-Problem-5)
- [Problem 6](#-Problem-6)

In [2]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_transformer
model = KNeighborsClassifier (n_neighbors=1) # k is complexity controller , as k=1 -model is overfitting , as k approaches n,
#it will simply return the class or category of majority of data points and hence becomes too simple .
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [6]:
default = pd.read_csv('/content/sample_data/default.csv')

In [37]:
default.head()

   Unnamed: 0 default student      balance        income
0           1      No      No   729.526495  44361.625074
1           2      No     Yes   817.180407  12106.134700
2           3      No      No  1073.549164  31767.138947
3           4      No      No   529.250605  35704.493935
4           5      No      No   785.655883  38463.495879

[Back to top](#-Index)

### Problem 1

#### Determine `X` and `y`


Define `X` as all columns except for `default` and `y` as `default` below.

In [38]:

X = default.drop(columns=['default'])
y = default['default']

# Answer check
print(X.head())
print('==============')
print(y.head())

   Unnamed: 0 student      balance        income
0           1      No   729.526495  44361.625074
1           2     Yes   817.180407  12106.134700
2           3      No  1073.549164  31767.138947
3           4      No   529.250605  35704.493935
4           5      No   785.655883  38463.495879
==============
0    No
1    No
2    No
3    No
4    No
Name: default, dtype: object

[Back to top](#-Index)

### Problem 2

#### Create train/test split



Use the `train_test_split` function to create a train test split on `X` and `y` with 25% of the data assigned as the test set.  Set `random_state = 42` to assure correct grading.

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y ,test_size=0.25, random_state=42)

# Answer check
print(X_train.shape)
print(X_test.shape)

(7500, 4)
(2500, 4)

[Back to top](#-Index)

### Problem 3

#### Column transformer for encoding `student` and scaling `['balance', 'income']`



Use the `make_column_transformer` to create a column transformer. Inside the `make_column_transformer` specify an instance of the `OneHotEncoder` transformer from scikit-learn. Inside `OneHotEncoder` set `drop` equal to `'if_binary'`. Apply this transformation to the `student` column. On the `remainder` columns, apply a `StandardScaler()` transformation.

 Assign your column transformer to `transformer` below.

[Documentation for `make_column_transformer`](https://scikit-learn.org/stable/modules/generated/sklearn.compose.make_column_transformer.html)

In [53]:
ohe=OneHotEncoder(drop='if_binary')
transformer = make_column_transformer(
        (ohe, ['student']),
        (StandardScaler(), ['balance','income']))

#Answer check
print(transformer)

ColumnTransformer(transformers=[('onehotencoder',
                                 OneHotEncoder(drop='if_binary'), ['student']),
                                ('standardscaler', StandardScaler(),
                                 ['balance', 'income'])])

[Back to top](#-Index)

### Problem 4

#### Pipeline with KNN and `n_neighbors = 5`



Using your column `transformer` defined above, create a `Pipeline` named `fivepipe` below with steps `transform` and `knn` that transform your columns and subsequently build a KNN model using `KNeighborsClassifier()`.  

Use the `fit` function to fit the pipe on the training data and use the `.score` method of the fit pipe to determine the accuracy on the test data.  Assign this to `fivepipe_acc` below.

In [76]:
fivepipe =''
fivepipe_acc = ''
knnmodel = KNeighborsClassifier(n_neighbors=5)
fivepipe = Pipeline(steps=[('transform',transformer ),('knn', knnmodel)])
fivepipe_model= fivepipe.fit(X_train,y_train)
fivepipe_acc= fivepipe_model.score(X_test,y_test)

# Answer check
print(fivepipe_acc)

0.968


[Back to top](#-Index)

### Problem 5

#### Pipeline with `n_neighbors = 50`



Using your column `transformer` defined above, create a `Pipeline` named `fiftypipe` below with steps `transform` and `knn` that transform your columns and subsequently build a KNN model using `KNeighborsClassifier()`. Build the KNN model with `n_neighbors = 50`

Use the `fit` function to fit the pipe on the training data and use the `.score` method of the fit pipe to determine the accuracy on the test data.  Assign this to `fiftypipe_acc` below.

In [72]:
fiftypipe = ''
fiftypipe_acc = ''
fiftypipe = Pipeline(steps = [("transform",transformer), ("knn",KNeighborsClassifier(n_neighbors=50))])
fiftypipe_model=fiftypipe.fit(X_train,y_train)
fiftypipe_acc =fiftypipe_model.score(X_test, y_test)# should be 0.9712
# Answer check
print(fiftypipe_acc)

0.9712

[Back to top](#-Index)

### Problem 6

#### False Predictions


Finally, compare the two pipelines based on the number of sum of the errors (FP+FN) -- those observations that the model predicted to default but incorrectly so. Assign these values as integers to `five_fp` and `fifty_fp`, respectively.   

(Hint: Add up the predictions of X_test that are not equal to y_test)

In [122]:
fifty_n_preds = fiftypipe_model.predict(X_test)
five_n_preds =  fivepipe_model.predict(X_test)
five_fp=''
fifty_fp=''


# Answer check
print(f'Number of False Predictions with five neighbors: {five_fp}')
print(f'Number of False Predictions with five neighbors: {fifty_fp}')

#y_test_df=pd.DataFrame(y_test).reset_index()
y_test_df

Number of False Predictions with five neighbors:
Number of False Predictions with five neighbors:

      index default
0      6252      No
1      4684      No
2      1731      No
3      4742      No
4      4521      No
...     ...     ...
2495   4862      No
2496   7025      No
2497   7647      No
2498   7161      No
2499     73      No

[2500 rows x 2 columns]