### Required Codio Assignment 21.1: Multiple Nodes

**Expected Time = 60 minutes**

**Total Points = 60**

This activity focuses on expanding the neural network to use three nodes for a prediction.  The main difference from your prior activity is that for each new node you will need a corresponding set of weights for features and bias.  Again, you will use a small sample of the Titanic dataset to test the networks forward pass.

#### Index

- [Problem 1](#-Problem-1)
- [Problem 2](#-Problem-2)
- [Problem 3](#-Problem-3)
- [Problem 4](#-Problem-4)
- [Problem 5](#-Problem-5)
- [Problem 6](#-Problem-6)

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns
titanic = sns.load_dataset('titanic').dropna(subset = ['age'])
X = titanic[['age', 'fare']].head()
y = titanic['survived'].head()

In [97]:
y

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

[Back to top](#-Index)

### Problem 1

#### Add bias

**10 Points**

In the code cell below, complete the definition of the `add_bias` function to add a column named `bias` of ones as the first column of your data `X`.

In [36]:
### GRADED

# YOUR CODE HERE
def add_bias(X):
    '''
    This function adds a bias feature
    as the lead column to an array X.
    '''
    X['bias']=np.ones(5)
    return X


### ANSWER CHECK
X_with_bias = add_bias(X)
X_with_bias= X_with_bias [['bias','age','fare']]
X_with_bias.head()

   bias   age     fare
0   1.0  22.0   7.2500
1   1.0  38.0  71.2833
2   1.0  26.0   7.9250
3   1.0  35.0  53.1000
4   1.0  35.0   8.0500

[Back to top](#-Index)

### Problem 2

#### A weight array

**10 Points**

Assuming that your ANN will have three layers, you will need to create weights for the bias and each feature in each node. In other words, for a three-node layer you will need three rows of three columns of weights.  

After setting a random seed seed with `42` for reproducibility, use the `NumPy` normal random function to create a `(3,3)` array containing the weights. Assign the result to the variable `weights`.

In [78]:
### GRADED
weights = ''
# YOUR CODE HERE
np.random.seed(42)
weights=np.random.normal(size=(3,3))

### ANSWER CHECK
print(weights.shape)
print(weights)

(3, 3)
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]

[Back to top](#-Index)

### Problem 3

#### Weighted Sum

**10 Points**

Below, use matrix multiplication to apply the `weights` to your data `X_with_bias` and assign the results to `layer_1_output` below.

In [79]:
### GRADED
layer_1_output = ''

# YOUR CODE HERE
layer_1_output=X_with_bias@weights

### ANSWER CHECK
print(layer_1_output)

            0          1          2
0   45.452664   0.274263  -7.907014
1  170.943350  45.669187 -41.715199
2   52.610752  -0.144332  -9.160457
3  137.658960  32.417152 -32.476195
4   66.515422  -2.155783 -11.326374

In [63]:
weights

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

[Back to top](#-Index)

### Problem 4

#### Activation

**10 Points**

After computing the weighted sum for the data you are to apply a sigmoid activation function.  Below, complete the definition of the `sigmoid` function that takes in an array of values and returns the result of applying the transformation:

$$f(x) = \frac{1}{1 + e^{-x}}$$

Finally, apply the `sigmoid` function to the array `layer_1_output` and assign the results to the variable `layer_1_activation`.

In [90]:
layer_1_output

            0          1          2
0   45.452664   0.274263  -7.907014
1  170.943350  45.669187 -41.715199
2   52.610752  -0.144332  -9.160457
3  137.658960  32.417152 -32.476195
4   66.515422  -2.155783 -11.326374

In [91]:
### GRADED

# YOUR CODE HERE
def sigmoid(x):
    return 1/(1+np.exp(-x))

layer_1_activation = sigmoid(layer_1_output)

### ANSWER CHECK
print(type(layer_1_activation))

<class 'pandas.core.frame.DataFrame'>

In [92]:
layer_1_activation

     0         1             2
0  1.0  0.568139  3.680168e-04
1  1.0  1.000000  7.643973e-19
2  1.0  0.463980  1.051038e-04
3  1.0  1.000000  7.866251e-15
4  1.0  0.103792  1.205072e-05

[Back to top](#-Index)

### Problem 5

#### Bias Term

**10 Points**


The array from above will need to again have weights applied, and these include a weight for a bias term.  


In the code cell below, apply the `add_bias` function to `layer_1_activation` and assign the resulting array to `layer_1_with_bias`.  Then create an appropriately sized array of weights for a single node named `weights_2` again using `np.random.seed(42)`.

The instruction is to create weights_2 for a single node (this is typically the output layer for a binary classification task). The input to this single node comes from layer_1_activation, which after adding a bias, becomes layer_1_with_bias. This layer_1_with_bias has 4 features (the new bias term plus the 3 outputs from the first hidden layer).

In [93]:
### GRADED
layer_1_with_bias = ''
weights_2 = ''
# YOUR CODE HERE
layer_1_with_bias = add_bias(layer_1_activation)
layer_1_with_bias.reset_index(drop=True,inplace=True)
# arrange the columns
layer_1_with_bias= layer_1_with_bias [['bias',0,1,2]]
np.random.seed(42)
weights_2 = np.random.normal(size=(4,1))#  a single output node receiving input from 4 features.

### ANSWER CHECK
print(layer_1_with_bias)
print(weights_2)

   bias    0         1             2
0   1.0  1.0  0.568139  3.680168e-04
1   1.0  1.0  1.000000  7.643973e-19
2   1.0  1.0  0.463980  1.051038e-04
3   1.0  1.0  1.000000  7.866251e-15
4   1.0  1.0  0.103792  1.205072e-05
[[ 0.49671415]
 [-0.1382643 ]
 [ 0.64768854]
 [ 1.52302986]]

[Back to top](#-Index)

### Problem 6

#### Output of First Pass

**10 Points**


Finally, use the weights and bias added data from the first layer to compute the weighted sum and pass the results through a sigmoid activation.  Use these results to predict the positive class if output > 0.5 and class 0 otherwise.  What is the accuracy on the dataset -- assign to `acc_first_pass` below.

In [94]:
layer_1_with_bias@weights_2

          0
0  0.726988
1  1.006138
2  0.659124
3  1.006138
4  0.425693

In [95]:
1/(1+np.exp(-2.298895))

np.float64(0.9087854820066565)

In [130]:
### GRADED
ans = ''
acc_first_pass = ''

# YOUR CODE HERE
ans=layer_1_with_bias@weights_2
output=sigmoid(ans)
opclass = np.where(output>0.5, 1,0)
acc_first_pass = 3/5

### ANSWER CHECK
print(acc_first_pass)
# compare y and opclass

0.6

In [132]:
opclass,y# 3 values match .

(array([[1],
        [1],
        [1],
        [1],
        [1]]),
 0    0
 1    1
 2    1
 3    1
 4    0
 Name: survived, dtype: int64)

Great job!  Obviously we hope to use a better approach than purely random weights -- this is where backpropogation comes in.  Next you will iteratively update these weights to hopefully improve the performance of the network.